[phases.setup]
nixPkgs = ["nodejs_18", "python3", "gcc", "g++", "make", "pkg-config"]

[phases.install]
cmds = [
  "npm config set python python3",
  "npm ci --omit=dev --build-from-source=better-sqlite3"
]

[phases.build]

[start]
cmd = "npm start"
